# Generated by Django 5.1.2 on 2024-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='peaks_image/'),
        ),
    ]
