# Generated by Django 5.1.2 on 2024-11-20 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'unique': 'A category with that name already exists!'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'unique': 'A post with that title already exists!'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Title must be at least 2 characters!')]),
        ),
    ]
