# Generated by Django 5.1.2 on 2024-12-09 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_picture_and_more'),
        ('posts', '0008_alter_post_post_image_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='accounts.profile'),
        ),
    ]
