# Generated by Django 5.1.2 on 2024-11-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type_of_climber', models.CharField(choices=[('Beginner', 'Beginner'), ('Mid', 'Mid'), ('Pro', 'Pro')], default='Beginner', max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
