# Generated by Django 5.1.2 on 2024-11-28 13:15

import theEndPoint.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[theEndPoint.accounts.validators.image_size_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_climber',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Mid', 'Mid'), ('Pro', 'Pro')], default='Beginner', max_length=8),
        ),
    ]
